# Generated by Django 3.1.1 on 2021-05-25 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 12, 55, 27, 715477)),
        ),
    ]
